---
- hosts: all
  environment:
    PATH: /usr/sbin:/sbin:{{ ansible_env.PATH }}
  become: yes
  become_method: su
  become_user: root
  roles:
    - { role: base, tags: [ 'role_base' ] }
    - { role: disable-selinux, tags: [ 'role_dis_selinux' ] }
    - { role: ssh, tags: [ 'role_ssh' ] }

# - hosts: kube_master
#   environment:
#     PATH: /usr/sbin:/sbin:{{ ansible_env.PATH }}
#   become: yes
#   become_method: su
#   become_user: root
#   roles:
#     - kube-master

# - hosts: kube_nodes
#   environment:
#   PATH: /usr/sbin:/sbin:{{ ansible_env.PATH }}
#   become: yes
#   become_method: su
#   become_user: root
#   roles:
#   - kube-workers
