---
- name: Install libselinux as prerequisite for SELinux Ansible module
  yum:
    name: "{{item}}"
    state: latest
  with_items:
    - libselinux-python
    - libsemanage-python
  become: true
  become_method: su
  become_user: root

- name: Disable SELinux 
  selinux:
    state: disabled
  become: true
  become_method: su
  become_user: root
