---

#- include_vars: users.yml

- name: Add users | create users, shell, home dirs
  user: name={{ item.username }} shell=/bin/bash createhome=yes comment='create with ansible'
  with_items: '{{users}}'
  become: true
  become_method: su
  become_user: root

- name: Setup | authorized key upload
  authorized_key: user={{ item.username }}
    key="{{ lookup('file', 'pub_keys/{{ item.username }}.pub') }}"
  with_items: '{{users}}'
  become: true
  become_method: su
  become_user: root

- name: common | install packages
  yum: name={{ item }} state=installed
  with_items:
      - git
      - vim
      - wget
  tags: common
  become: true
  become_method: su
  become_user: root

