---

#- include_vars: users.yml

- name: Add users | create users, shell, home dirs
  user: name={{ item }} shell=/bin/bash createhome=yes comment='create with ansible'
  with_items: '{{users.username.keys()|list}}'
  become: true
  become_method: su
  become_user: root

- name: Setup | authorized key upload
  authorized_key: user={{ item }}
    key="{{ lookup('file', 'pub_keys/{{ item }}.pub') }}"
  with_items: '{{users.username.keys()| list}}'
  become: true
  become_method: su
  become_user: root


