---
  - name: 1.Check if EPEL repo is already configured.
    stat: path={{ epel_repofile_path }}
    register: epel_repofile_result
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
   
  - name: 2.Install EPEL repo.
    yum:
      name: "{{ epel_repo_url }}"
      state: present
    register: result
    when: not epel_repofile_result.stat.exists and (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')
    become: true
    become_method: su
    become_user: root
   
  - name: 3.Import EPEL GPG key.
    rpm_key:
      key: "{{ epel_repo_gpg_key_url }}"
      state: present
    when: not epel_repofile_result.stat.exists and (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')
    become: true
    become_method: su
    become_user: root

  - name: common | install packages
    yum: name={{ item }} state=installed
    with_items:
        - git
        - vim
        - wget
        - atop
        - strace
        - htop
        - ethtool
        - lsof
        - sysstat
        - tmux
        - nmap
        - gcc-c++
        - net-tools 
        - bind-utils
        - traceroute
        - mdadm
        - zsh
        - tcpdump
    tags: common
    become: true
    become_method: su
    become_user: root
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
